export const countries = [
  'Afghanistan',
  'Albanie',
  'Algérie',
  'Andorre',
  'Angola',
  'Antigua-et-Barbuda',
  'Arabie saoudite',
  'Argentine',
  'Arménie',
  'Australie',
  'Autriche',
  'Azerbaïdjan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbade',
  'Belgique',
  'Belize',
  'Bénin',
  'Bhoutan',
  'Biélorussie',
  'Birmanie',
  'Bolivie',
  'Bosnie-Herzégovine',
  'Botswana',
  'Brésil',
  'Brunei',
  'Bulgarie',
  'Burkina Faso',
  'Burundi',
  'Cambodge',
  'Cameroun',
  'Canada',
  ' Cap-Vert',
  ' République centrafricaine',
  ' Chili',
  'Chine',
  'Chypre',
  'Colombie',
  'Comores',
  'Congo-Brazzaville',
  'Congo-Kinshasa',
  ' Corée du Nord',
  'Corée du Sud',
  'Costa Rica',
  'Côte d Ivoire',
  'Croatie',
  ' Cuba',
  ' Danemark',
  ' Djibouti',
  'Dominique',
  'Égypte',
  ' Émirats arabes unis',
  'Équateur',
  'Érythrée',
  'Espagne',
  ' Estonie',
  'États-Unis',
  ' Éthiopie',
  ' Fidji',
  'Finlande',
  'France',
  ' Gabon',
  ' Gambie',
  'Géorgie',
  'Ghana',
  'Grèce',
  'Grenade',
  'Guatemala',
  'Guinée',
  'Guinée équatoriale',
  'Guinée-Bissau',
  'Guyana',
  'Haïti',
  'Honduras',
  'Hongrie',
  'Îles Cook',
  'Îles Marshall',
  ' Inde',
  ' Indonésie',
  ' Iraq',
  'Irlande',
  'Islande',
  ' Israël',
  'Italie',
  'Jamaïque',
  'Japon',
  'Jordanie',
  'Kazakhstan',
  ' Kenya',
  ' Kirghizstan',
  ' Koweït',
  'Laos',
  ' Lesotho',
  'Lettonie',
  'Liban',
  ' Liberia',
  ' Libye',
  ' Liechtenstein',
  'Lituanie',
  'Luxembourg',
  'Macédoine',
  'Madagascar',
  'Malaisie',
  'Malawi',
  ' Maldives',
  ' Mali',
  'Malte',
  'Maroc',
  ' Maurice',
  'Mauritanie',
  'Mexique',
  ' Moldavie',
  ' Monaco',
  'Mongolie',
  'Mozambique',
  ' Namibie',
  ' Népal',
  'Nicaragua',
  ' Niger',
  'Nigeria',
  ' Norvège',
  'Nouvelle Zélande',
  ' Oman',
  'Ouganda',
  'Ouzbékistan',
  'Pakistan',
  'Panama',
  'Papouasie-Nouvelle-Guinée',
  'Paraguay',
  'Pays-Bas',
  'Pérou',
  ' Philippines',
  'Pologne',
  'Portugal',
  ' Qatar',
  ' Roumanie',
  'Royaume-Uni',
  'Russie',
  ' Rwanda',
  'Saint-Kitts-et-Nevis',
  'Sainte-Lucie',
  ' Saint-Vincent-et-les-Grenadines',
  'Salvador',
  ' Samoa',
  'São Tomé-et-Príncipe',
  ' Sénégal',
  'Serbie',
  'Seychelles',
  'Sierra Leone',
  'Singapour',
  ' Slovaquie',
  'Slovénie',
  'Somalie',
  'Soudan',
  'Sri Lanka',
  'Suède',
  'Suisse',
  ' Suriname',
  'Swaziland',
  'Syrie',
  'Tadjikistan',
  'Tanzanie',
  'Tchad',
  'Thaïlande',
  'Togo',
  'Tonga',
  'Trinité-et-Tobago',
  'Tunisie',
  'Turkménistan',
  'Turquie',
  'Tuvalu',
  'Ukraine',
  'Uruguay',
  'Venezuela',
  'Vietnam',
  'Yémen',
  'Zambie',
  'Zimbabwe',
]